name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'
  release:
    types:
      - created

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  doc:
    name: Documentation
    runs-on: ubuntu-latest
    container:
      image: python:3.8
      env:
        LANG: C.UTF-8
    steps:
      - uses: actions/checkout@v4
      - name: Documentation
        run: |
          cd docs/
          pip install -r ./requirements.txt -U
          make html SPHINXOPTS="-W"
