name: Linting

on:
  pull_request:
    paths:
      - 'geotrek/**'  # if geotrek code change
      - '.github/workflows/lint.yml'  # if lint workflow change
      - 'dev-requirements.txt'  # if dev-requirements.txt change
      - 'setup.cfg'   # if lint tools configuration change

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  flake8:
    name: Checking Flake8 rules
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04']
        python-version: ['3.8']

    steps:
      - uses: actions/checkout@v4

      - name: Not evaluated values in migration files
        run: |
          test $(ls geotrek/*/migrations/*.py | xargs grep -l srid | xargs grep -L SRID | wc -l) -eq 0


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.wheel_dir

          key: pip-${{ matrix.python-version }}
          restore-keys: |
            pip-${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip3 wheel --wheel-dir=~/.wheel_dir flake8 -c dev-requirements.txt
          pip3 install --find-links=~/.wheel_dir --upgrade flake8 -c dev-requirements.txt

      - name: Flake8
        run: |
          flake8 geotrek
